In [217]:
import requests
import pandas as pd
import numpy as np

In [218]:
url = 'https://www.fundsexplorer.com.br/ranking'

In [219]:
response = requests.get(url)
if response.status_code == 200:
    df = pd.read_html(response.content, encoding='utf-8')[0]

In [220]:
df.sort_values('Códigodo fundo', inplace=True)

In [221]:
df.describe(include="all")

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
count,319,301,311,3.110000e+02,319,314,314,314,314,314,...,305,305,298.000000,255,255,255,255,125,30,319.000000
unique,308,11,290,NaN,132,110,182,211,225,110,...,294,289,NaN,113,63,145,160,73,18,NaN
top,RSPD11,Títulos e Val. Mob.,"R$ 10,03",NaN,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 171.070.236,81","R$ 1.148,04",NaN,"0,63%","0,00%","0,63%","0,63%","0,00%","0,00%",NaN
freq,9,92,5,NaN,11,36,42,48,62,42,...,9,9,NaN,13,181,11,11,43,13,NaN
mean,NaN,NaN,NaN,2.791654e+04,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,82.573826,NaN,NaN,NaN,NaN,NaN,NaN,2.793103
std,NaN,NaN,NaN,1.864733e+05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,61.570766,NaN,NaN,NaN,NaN,NaN,NaN,7.342121
min,NaN,NaN,NaN,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-76.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,1.580000e+02,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,68.250000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
50%,NaN,NaN,NaN,2.223000e+03,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,83.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
75%,NaN,NaN,NaN,1.644150e+04,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,94.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000
max,NaN,NaN,NaN,3.180000e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,946.000000,NaN,NaN,NaN,NaN,NaN,NaN,72.000000

Dados Categoricos

In [222]:
categorical_columns = ["Códigodo fundo", "Setor"]

In [223]:
idx = df[df['Setor'].isna()].index
df.drop(idx, inplace=True)

In [224]:
df[categorical_columns].isna().sum()

Códigodo fundo    0
Setor             0
dtype: int64

In [225]:
df[categorical_columns] = df[categorical_columns].astype("category")

In [226]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 301 entries, 213 to 308
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           301 non-null    category
 1   Setor                    301 non-null    category
 2   Preço Atual              293 non-null    object
 3   Liquidez Diária          293 non-null    float64
 4   Dividendo                301 non-null    object
 5   DividendYield            296 non-null    object
 6   DY (3M)Acumulado         296 non-null    object
 7   DY (6M)Acumulado         296 non-null    object
 8   DY (12M)Acumulado        296 non-null    object
 9   DY (3M)Média             296 non-null    object
 10  DY (6M)Média             296 non-null    object
 11  DY (12M)Média            296 non-null    object
 12  DY Ano                   266 non-null    object
 13  Variação Preço           296 non-null    object
 14  Rentab.Período           296 non-null    object
 15  Rentab.Acumulada         296 non-null    object
 16  PatrimônioLíq.           298 non-null    object
 17  VPA                      298 non-null    object
 18  P/VPA                    291 non-null    float64
 19  DYPatrimonial            248 non-null    object
 20  VariaçãoPatrimonial      248 non-null    object
 21  Rentab. Patr.no Período  248 non-null    object
 22  Rentab. Patr.Acumulada   248 non-null    object
 23  VacânciaFísica           125 non-null    object
 24  VacânciaFinanceira       30 non-null     object
 25  QuantidadeAtivos         301 non-null    int64
dtypes: category(2), float64(2), int64(1), object(21)
memory usage: 70.4+ KB

Dados numericos

In [227]:
#  pega todas as colunas a partir da 2 coluna e menos a ultima coluna
col_floats = list(df.iloc[:,2:-1].columns)

In [228]:
# substituir dados NaN por 0
df[col_floats] = df[col_floats].fillna(value=0)

In [229]:
df[col_floats]

,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,...,Rentab.Acumulada,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira
213,"R$ 66,98",2578.0,"R$ 0,50","0,77%","2,34%","4,49%","9,00%","0,78%","0,75%","0,75%",...,"-1,41%","R$ 430.917.128,00","R$ 91,51",73.0,"0,55%","0,00%","0,55%","0,55%","7,50%",0
59,"R$ 93,70",4814.0,"R$ 1,05","1,12%","3,16%","6,37%","14,39%","1,05%","1,06%","1,20%",...,"1,12%","R$ 286.309.475,82","R$ 94,82",99.0,"1,01%","-0,94%","0,06%","5,00%",0,0
260,"R$ 63,05",7975.0,"R$ 0,75","1,22%","3,39%","6,46%","12,76%","1,13%","1,08%","1,06%",...,"-6,08%","R$ 454.619.127,52","R$ 94,22",67.0,"0,19%","0,00%","0,19%","0,19%","0,00%",0
3,"R$ 800,51",3.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"-28,29%","R$ 224.603.756,71","R$ 2.020,24",40.0,0,0,0,0,"64,05%",0
68,"R$ 85,00",1361.0,"R$ 0,87","1,10%","1,10%","3,45%","10,46%","0,37%","0,58%","0,87%",...,"1,10%","R$ 66.447.316,94","R$ 96,13",88.0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,"R$ 25,79",13653.0,"R$ 0,10","0,33%","2,18%","4,52%","8,96%","0,73%","0,75%","0,75%",...,"-6,18%","R$ 545.397.975,50","R$ 74,55",35.0,"0,40%","0,00%","0,40%","0,40%","46,00%","0,00%"
188,"R$ 6,98",117997.0,"R$ 0,08","1,09%","3,13%","6,21%","11,98%","1,04%","1,03%","1,00%",...,"-1,66%","R$ 369.792.382,05","R$ 8,54",82.0,"0,90%","-4,04%","-3,18%","-89,40%",0,0
2,"R$ 8,82",2223.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"-37,83%","R$ 27.688.895,17","R$ 13,26",67.0,0,0,0,0,"0,00%","100,00%"
21,0,0.0,"R$ 0,63","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"0,00%","R$ 51.031.566,94","R$ 103,59",0.0,0,0,0,0,0,0
308,"R$ 126,00",10.0,"R$ 1,05","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"0,00%",0,0,0.0,0,0,0,0,0,0

In [230]:
df[col_floats].head()

,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,...,Rentab.Acumulada,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira
213,"R$ 66,98",2578.0,"R$ 0,50","0,77%","2,34%","4,49%","9,00%","0,78%","0,75%","0,75%",...,"-1,41%","R$ 430.917.128,00","R$ 91,51",73.0,"0,55%","0,00%","0,55%","0,55%","7,50%",0
59,"R$ 93,70",4814.0,"R$ 1,05","1,12%","3,16%","6,37%","14,39%","1,05%","1,06%","1,20%",...,"1,12%","R$ 286.309.475,82","R$ 94,82",99.0,"1,01%","-0,94%","0,06%","5,00%",0,0
260,"R$ 63,05",7975.0,"R$ 0,75","1,22%","3,39%","6,46%","12,76%","1,13%","1,08%","1,06%",...,"-6,08%","R$ 454.619.127,52","R$ 94,22",67.0,"0,19%","0,00%","0,19%","0,19%","0,00%",0
3,"R$ 800,51",3.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"-28,29%","R$ 224.603.756,71","R$ 2.020,24",40.0,0,0,0,0,"64,05%",0
68,"R$ 85,00",1361.0,"R$ 0,87","1,10%","1,10%","3,45%","10,46%","0,37%","0,58%","0,87%",...,"1,10%","R$ 66.447.316,94","R$ 96,13",88.0,0,0,0,0,0,0

In [231]:
# Substituir simbolos por outros tudo de uma vez na tabela (poderia fazer atraves de codigos Regex)
df[col_floats] = df[col_floats].applymap(lambda x: str(x).replace('R$', '').replace('.0', '').replace('.', '').replace('%', '').replace(',', '.'))

In [232]:
df[col_floats] = df[col_floats].astype('float')

In [233]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 301 entries, 213 to 308
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           301 non-null    category
 1   Setor                    301 non-null    category
 2   Preço Atual              301 non-null    float64
 3   Liquidez Diária          301 non-null    float64
 4   Dividendo                301 non-null    float64
 5   DividendYield            301 non-null    float64
 6   DY (3M)Acumulado         301 non-null    float64
 7   DY (6M)Acumulado         301 non-null    float64
 8   DY (12M)Acumulado        301 non-null    float64
 9   DY (3M)Média             301 non-null    float64
 10  DY (6M)Média             301 non-null    float64
 11  DY (12M)Média            301 non-null    float64
 12  DY Ano                   301 non-null    float64
 13  Variação Preço           301 non-null    float64
 14  Rentab.Período           301 non-null    float64
 15  Rentab.Acumulada         301 non-null    float64
 16  PatrimônioLíq.           301 non-null    float64
 17  VPA                      301 non-null    float64
 18  P/VPA                    301 non-null    float64
 19  DYPatrimonial            301 non-null    float64
 20  VariaçãoPatrimonial      301 non-null    float64
 21  Rentab. Patr.no Período  301 non-null    float64
 22  Rentab. Patr.Acumulada   301 non-null    float64
 23  VacânciaFísica           301 non-null    float64
 24  VacânciaFinanceira       301 non-null    float64
 25  QuantidadeAtivos         301 non-null    int64
dtypes: category(2), float64(23), int64(1)
memory usage: 70.4 KB

In [234]:
df.describe()

,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
count,301.000000,3.010000e+02,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,...,3.010000e+02,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000
mean,211.624585,2.750125e+04,6.082193,1.225714,2.884551,5.039900,9.620365,0.961495,0.839934,0.801628,...,4.282602e+08,517.245415,79.614618,0.736877,-0.333821,0.398638,0.325947,6.111628,1.111993,2.960133
std,1336.685087,1.894236e+05,66.699320,6.612280,6.894484,7.182617,8.467417,2.297930,1.197196,0.705761,...,7.887542e+08,4216.197649,62.991515,1.103438,6.226843,6.346848,9.435263,16.196504,7.267228,7.526292
min,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.253695e+07,-16.530000,-76.000000,0.000000,-89.900000,-89.790000,-89.790000,0.000000,0.000000,0.000000
25%,48.210000,1.320000e+02,0.440000,0.620000,1.900000,3.630000,7.140000,0.630000,0.610000,0.590000,...,5.891648e+07,79.170000,65.000000,0.350000,0.000000,0.000000,0.210000,0.000000,0.000000,0.000000
50%,78.000000,2.004000e+03,0.750000,0.910000,2.710000,5.090000,10.270000,0.900000,0.850000,0.860000,...,1.816055e+08,96.330000,82.000000,0.650000,0.000000,0.570000,0.680000,0.000000,0.000000,0.000000
75%,97.300000,1.365300e+04,1.020000,1.100000,3.270000,6.210000,12.880000,1.090000,1.030000,1.070000,...,4.035620e+08,116.360000,93.000000,0.900000,0.000000,0.860000,1.140000,2.000000,0.000000,2.000000
max,21775.000000,3.180000e+06,1149.150000,114.860000,116.710000,119.510000,123.940000,38.900000,19.920000,10.330000,...,7.509519e+09,65128.340000,946.000000,13.370000,57.540000,58.430000,15.810000,100.000000,100.000000,72.000000

In [235]:
# procurar por valores infinitos no dataframe
df[np.isinf(df[col_floats]).any(1)]

# Caso haja valor infinito... o codigo abaixo exclui o ativo com valor infinito
# idx = df[np.isinf(df[col_floats]).any(1)].index
# df.drop(idx, inplace=True)

Empty DataFrame
Columns: [Códigodo fundo, Setor, Preço Atual, Liquidez Diária, Dividendo, DividendYield, DY (3M)Acumulado, DY (6M)Acumulado, DY (12M)Acumulado, DY (3M)Média, DY (6M)Média, DY (12M)Média, DY Ano, Variação Preço, Rentab.Período, Rentab.Acumulada, PatrimônioLíq., VPA, P/VPA, DYPatrimonial, VariaçãoPatrimonial, Rentab. Patr.no Período, Rentab. Patr.Acumulada, VacânciaFísica, VacânciaFinanceira, QuantidadeAtivos]
Index: []

[0 rows x 26 columns]

In [236]:
df['P/VPA'] = df['P/VPA']/100

In [250]:
df.head()

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
213,ABCP11,Shoppings,66.98,2578.0,0.50,0.77,2.34,4.49,9.00,0.78,...,4.309171e+08,91.51,0.73,0.55,0.00,0.55,0.55,7.50,0.0,1
59,AFHI11,Títulos e Val. Mob.,93.70,4814.0,1.05,1.12,3.16,6.37,14.39,1.05,...,2.863095e+08,94.82,0.99,1.01,-0.94,0.06,5.00,0.00,0.0,0
260,AIEC11,Lajes Corporativas,63.05,7975.0,0.75,1.22,3.39,6.46,12.76,1.13,...,4.546191e+08,94.22,0.67,0.19,0.00,0.19,0.19,0.00,0.0,2
3,ALMI11,Lajes Corporativas,800.51,3.0,0.00,0.00,0.00,0.00,0.00,0.00,...,2.246038e+08,220.24,0.40,0.00,0.00,0.00,0.00,64.05,0.0,1
68,ALZM11,Títulos e Val. Mob.,85.00,1361.0,0.87,1.10,1.10,3.45,10.46,0.37,...,6.644732e+07,96.13,0.88,0.00,0.00,0.00,0.00,0.00,0.0,0

Analisando Média por setor

In [238]:
df.columns

Index(['Códigodo fundo', 'Setor', 'Preço Atual', 'Liquidez Diária',
       'Dividendo', 'DividendYield', 'DY (3M)Acumulado', 'DY (6M)Acumulado',
       'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média', 'DY (12M)Média',
       'DY Ano', 'Variação Preço', 'Rentab.Período', 'Rentab.Acumulada',
       'PatrimônioLíq.', 'VPA', 'P/VPA', 'DYPatrimonial',
       'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
       'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
       'QuantidadeAtivos'],
      dtype='object')

In [239]:
indicadores = ['Códigodo fundo', 'Setor', "Preço Atual", 'Liquidez Diária', "Dividendo", 
               'DY (12M)Acumulado', 'P/VPA', 'VacânciaFísica', 'VacânciaFinanceira',  'QuantidadeAtivos' ]

In [240]:
df_aux = df[indicadores]

In [241]:
df_aux

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DY (12M)Acumulado,P/VPA,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
213,ABCP11,Shoppings,66.98,2578.0,0.50,9.00,0.73,7.50,0.0,1
59,AFHI11,Títulos e Val. Mob.,93.70,4814.0,1.05,14.39,0.99,0.00,0.0,0
260,AIEC11,Lajes Corporativas,63.05,7975.0,0.75,12.76,0.67,0.00,0.0,2
3,ALMI11,Lajes Corporativas,800.51,3.0,0.00,0.00,0.40,64.05,0.0,1
68,ALZM11,Títulos e Val. Mob.,85.00,1361.0,0.87,10.46,0.88,0.00,0.0,0
...,...,...,...,...,...,...,...,...,...,...
211,XPPR11,Outros,25.79,13653.0,0.10,8.96,0.35,46.00,0.0,4
188,XPSF11,Outros,6.98,117997.0,0.08,11.98,0.82,0.00,0.0,0
2,XTED11,Lajes Corporativas,8.82,2223.0,0.00,0.00,0.67,0.00,100.0,1
21,YUFI11B,Residencial,0.00,0.0,0.63,0.00,0.00,0.00,0.0,0
308,ZAVI11,Híbrido,126.00,10.0,1.05,0.00,0.00,0.00,0.0,0

In [242]:
# Seapra por setor e pega a media e o desvio padrao de cada setor
# media_setor = df_aux.groupby('Setor').agg(['mean', 'std'])

In [243]:
# media_setor

In [248]:
def oportunidade_media():
    
#     media_setor = df_aux.groupby('Setor').agg(['mean','std'])
    
#     df_setor = df[df[label_setor].isin([setor])]
#     df['Liquidez Diária'] = df['Liquidez Diária'] * df['Preço Atual']
    
    filter_ = \
        (df['QuantidadeAtivos'] > 6) &\
        (df['Liquidez Diária'] > 4500) &\
        (df['P/VPA'] < 1.1) &\
        (df['DY (12M)Acumulado'] > df['DY (12M)Acumulado'].mean())  
            
    print('média de Ativos: {}'.format(df['QuantidadeAtivos'].mean()))
    print('média de Liquidez Diária: {}'.format(df['Liquidez Diária'].mean()))
    print('média de P/VPA: {}'.format(df['P/VPA'].mean()))
    print('média de DY (12M) Acumulado: {}'.format(df['DY (12M)Acumulado'].mean()))

    
    return df_aux[filter_]

In [249]:
oportunidade = oportunidade_media()
oportunidade.sort_values('Liquidez Diária', ascending=False, inplace=True)
oportunidade

média de Ativos: 2.9601328903654487
média de Liquidez Diária: 27501.25249169435
média de P/VPA: 0.7961461794019932
média de DY (12M) Acumulado: 9.620365448504984

C:\Users\lukin\AppData\Local\Temp\ipykernel_18412\98970188.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oportunidade.sort_values('Liquidez Diária', ascending=False, inplace=True)

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DY (12M)Acumulado,P/VPA,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
201,RZTR11,Híbrido,85.20,31600.0,0.85,13.77,0.88,0.0,0.0,10
239,HGLG11,Logística,160.49,27101.0,1.10,10.01,1.05,6.9,6.5,17
207,HGRU11,Híbrido,115.80,24246.0,0.85,9.74,0.94,0.0,0.0,17
245,TRXF11,Outros,102.85,18747.0,0.85,10.27,0.99,0.0,0.0,44
267,GGRC11,Logística,102.01,18603.0,0.95,10.17,0.82,0.0,0.0,20
259,BBPO11,Lajes Corporativas,82.70,16196.0,0.90,12.63,0.82,0.0,0.0,64
74,ALZR11,Logística,112.10,10871.0,0.81,12.31,1.05,0.0,0.0,15
285,RECT11,Híbrido,51.04,9134.0,0.54,10.56,0.55,15.1,0.0,8
79,BTAL11,Outros,84.80,7977.0,0.83,10.38,0.80,0.0,0.0,7
182,RBVA11,Outros,91.11,5810.0,0.95,12.79,0.85,0.7,0.0,72